using Godot;
using Jmo.AI.Affinities;
using System.Collections.Generic;
using System.Linq;

namespace Jmo.AI.Affinities;

/// <summary>
/// A powerful steering modifier that scales directional scores based on an AI's affinity.
/// It uses a Curve resource to translate an affinity value into a multiplier, allowing designers
/// to visually sculpt how personality traits affect movement choices.
/// </summary>
[GlobalClass]
public partial class AffinitySteeringModifier : SteeringConsiderationModifier
{
    [Export] private Affinity _affinityToMeasure;
    [Export] private Curve _responseCurve;

    public override void Modify(ref Dictionary<Vector3, float> scores, DecisionContext context, IBlackboard blackboard)
    {
        if (_responseCurve == null) return;
        var affinities = blackboard.GetVar<AIAffinitiesComponent>(BBDataSig.Affinities);
        if (affinities == null) return;

        // 1. Get the affinity value and sample the curve to get a global multiplier.
        float affinityValue = affinities.GetAffinity(_affinityToMeasure);
        float multiplier = _responseCurve.SampleBaked(affinityValue);

        // 2. Apply this multiplier to all scores generated by the consideration.
        //    This amplifies or diminishes the consideration's overall influence.
        foreach (var key in scores.Keys.ToList())
        {
            scores[key] *= multiplier;
        }
    }
}